# Generated by Django 5.2.10 on 2026-02-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuaros',
            new_name='Usuario',
        ),
    ]
